apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o .k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o .k8s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/elastic: "true"
        io.kompose.service: logstash
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOST_PORT
              value: 'https://:'
            - name: ELASTIC_PASSWORD
            - name: ELASTIC_USERNAME
            - name: LS_JAVA_OPTS
              value: -Xmx -Xms -Dlog4j2.formatMsgNoLookups=true
          image: 'elastdocker/logstash:'
          livenessProbe:
            exec:
              command:
                - curl
                - -s
                - -XGET
                - http://127.0.0.1:9600
          name: logstash
          ports:
            - containerPort: 5044
            - containerPort: 9600
          resources: {}
          volumeMounts:
            - mountPath: /certs
              name: elastic.ca
            - mountPath: /usr/share/logstash/config/logstash.yml
              name: logstash-claim0
              readOnly: true
            - mountPath: /usr/share/logstash/config/pipelines.yml
              name: logstash-claim1
              readOnly: true
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-claim2
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: elastic.ca
          secret:
            items:
              - key: elastic.ca
                path: ca.crt
            secretName: elastic.ca
        - name: logstash-claim0
          persistentVolumeClaim:
            claimName: logstash-claim0
            readOnly: true
        - name: logstash-claim1
          persistentVolumeClaim:
            claimName: logstash-claim1
            readOnly: true
        - name: logstash-claim2
          persistentVolumeClaim:
            claimName: logstash-claim2
            readOnly: true
status: {}
